### obetener todos los services.
GET http://localhost:3000/api/services

### obtener un direction por _id
GET http://localhost:3000/api/services/65455630b91995929b068087

### crear un nuevo service
POST http://localhost:3000/api/services
Content-Type: application/json

{
    "description": "2 pages web",
    "price": 830
}

###modificar un service con patch (parcial)
PATCH http://localhost:3000/api/services/65455630b91995929b068087
Content-Type: application/json

{
  "price": 810
}

### delete service
DELETE http://localhost:3000/api/services/65455630b91995929b068087