### obetener todos los servicetypes.
GET http://localhost:3000/api/serviceTypes

### obtener un serviceTpye por serviceTypeId
GET http://localhost:3000/api/serviceTypes/65455b31ee9c14f47a631b04

### crear un nuevo serviceType
POST http://localhost:3000/api/serviceTypes
Content-Type: application/json

{
    "name": "Fashion"
}

###modificar un serviceType con patch (parcial)
PATCH http://localhost:3000/api/serviceTypes/65455b31ee9c14f47a631b04
Content-Type: application/json

{
  "name": "Name change"
}

### delete serviceType
DELETE http://localhost:3000/api/serviceTypes/65455b31ee9c14f47a631b04