### obetener todos los addres.
GET http://localhost:3000/api/addresses

### obtener un direction por addressId
GET http://localhost:3000/api/addresses/65453d292baabc0bc01a1359

### crear un nuevo addres
POST http://localhost:3000/api/addresses
Content-Type: application/json

{
    "street": "Balcarce",
    "streetNumber": -38,
    "country": "Argentina",
    "city": "Rosario"
}

###modificar un addres con patch (parcial)
PATCH http://localhost:3000/api/addresses/65453d292baabc0bc01a1359
Content-Type: application/json

{
  "streetNumber": 1890
}

### delete address
DELETE http://localhost:3000/api/addresses/65453d292baabc0bc01a1359