### obetener todos los addres.
GET http://localhost:3000/api/addresses

### obtener un direction por addressId
GET http://localhost:3000/api/addresses/18ae015c-4a0b-42bc-97a3-1a1d0b4f82ef

### crear un nuevo addres
POST http://localhost:3000/api/addresses
Content-Type: application/json

{
    "street": "Balcarce",
    "streetNumber": -38,
    "country": "Argentina",
    "city": "Rosario"
}

###modificar un addres con patch (parcial)
PATCH http://localhost:3000/api/addresses/18ae015c-4a0b-42bc-97a3-1a1d0b4f82ef
Content-Type: application/json

{
  "streetNumber": 1890
}

### delete address
DELETE http://localhost:3000/api/addresses/dbaca7f1-fc6a-4154-9fea-f0859caba252