### obetener todos los users.
GET http://localhost:3000/api/directions

### obtener un direction por directionId
GET http://localhost:3000/api/directions/1d504d77-a3ad-4542-951a-a9385f0f1898

### crear un nuevo direction
POST http://localhost:3000/api/directions
Content-Type: application/json

{
    "street": "Balcarce",
    "strNumber": -38,
    "country": "Argentina",
    "city": "Rosario"
}

### modificar un direction con put (total)
PUT http://localhost:3000/api/directions/1d504d77-a3ad-4542-951a-a9385f0f1898
Content-Type: application/json

{
    "street": "La Paz",
    "strNumber": 1232,
    "country": "Argentina",
    "city": "Rosario"
}

###modificar un direction con patch (parcial)
PATCH http://localhost:3000/api/directions/6ccf2185-e2ed-4dd5-913f-d604e38fafac
Content-Type: application/json

{
  "strNumber": 1890
}

### borrar un character
DELETE http://localhost:3000/api/directions/1e04719a-2ed3-4a6e-8943-cbb6fc78f6f8