### obetener todos los posts.
GET http://localhost:3000/api/posts

### obtener un post por postId
GET http://localhost:3000/api/posts/654e7f21400c77a98c3ccf46

### crear un nuevo post
POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "content": "este es un post creado.",
    "likes": 110,
    "rePosts": 43,
    "media": "imgPostcreadov2.jpg",
    "postType": "Without service",
    "date": "09/12/2018"
}

###modificar un post con patch (parcial)
PATCH http://localhost:3000/api/posts/654549b1a9457c0a4745cf6c
Content-Type: application/json

{
  "likes": 91218
}

### delete post
DELETE http://localhost:3000/api/posts/654549b1a9457c0a4745cf6c