### obetener todos los users.
GET http://localhost:3000/api/users

### obtener un user por _id
GET http://localhost:3000/api/users/6543f7ed22939aa00b6f3112

### crear un nuevo user
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "JuanPerez",
    "phone": 3415087211,
    "mail": "juanperez@gmail.com",
    "username": "j.perez",
    "password": "pa$$w0rd",
    "profileImg": "/img004",
    "description": "Me llamo Juan"
}

###modificar un user con patch (parcial)
PATCH http://localhost:3000/api/users/6543f89f751cd68be7870a86
Content-Type: application/json

{
  "name": "Guidito123",
  "mail": "guidito123@gmail.com"
}

### delete user
DELETE http://localhost:3000/api/users/654405072394cee5096aea9b