### obetener todos los users.
GET http://localhost:3000/api/users

### obtener un direction por userId
GET http://localhost:3000/api/users/69bc83ff-e578-4bba-b735-bc2e6447d922

### crear un nuevo user
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "nameSurname": "MarcosPerez",
    "phone": 3415093210,
    "mail": "marcosperez@gmail.com",
    "username": "m.perez",
    "password": "contrasen1a",
    "profileImg": "/img003",
    "description": "Me llamo Marcos"
}

###modificar un user con patch (parcial)
PATCH http://localhost:3000/api/users/69bc83ff-e578-4bba-b735-bc2e6447d922
Content-Type: application/json

{
  "nameSurname": "Guidito123",
  "mail": "guidito123@gmail.com"
}

### delete user
DELETE http://localhost:3000/api/users/69bc83ff-e578-4bba-b735-bc2e6447d922