### obetener todos los users.
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTRkMzkyMzk2YzY0MDRjN2M5M2VlY2EiLCJpYXQiOjE2OTk1NTk3MTV9.SL8go6nw49PyjK9qJa6sf81Ek4RDT-vCCoPA99x34QM

### obtener un user por _id
GET http://localhost:3000/api/users/6543f7ed22939aa00b6f3112

### crear un nuevo user
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "JuanPerez",
    "phone": 341,
    "email": 6,
    "username": "j.perez",
    "password": "pa$$w0rd",
    "profileImg": "/img004",
    "description": "Me llamo Juan"
}

###modificar un user con patch (parcial)
PATCH http://localhost:3000/api/users/655d03dd4c4ce18ad0a0aded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTRkMzkyMzk2YzY0MDRjN2M5M2VlY2EiLCJpYXQiOjE2OTk1NTk3MTV9.SL8go6nw49PyjK9qJa6sf81Ek4RDT-vCCoPA99x34QM
Content-Type: application/json

{
  "posts": []
}

### delete user
DELETE http://localhost:3000/api/users/655d017a4c4ce18ad0a0ade5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTRkMzkyMzk2YzY0MDRjN2M5M2VlY2EiLCJpYXQiOjE2OTk1NTk3MTV9.SL8go6nw49PyjK9qJa6sf81Ek4RDT-vCCoPA99x34QM